import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
function App() {
  const [products, setProducts] = useState([]); const [cart, setCart] = useState([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState('Toutes'); const [sent, setSent] = useState(false);
  useEffect(() => { fetch(`${API}/products?search=${encodeURIComponent(search)}&category=${encodeURIComponent(category)}`).then(r => r.json()).then(r => setProducts(r.data)).catch(() => setProducts([])); }, [search, category]);
  const add = (product) => setCart(items => { const found = items.find(i => i.id === product.id); return found ? items.map(i => i.id === product.id ? {...i, quantity: i.quantity + 1} : i) : [...items, {...product, quantity: product.minimumOrder}; });
  const submit = async () => { if (!cart.length) return; const response = await fetch(`${API}/quotes`, { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ destination: 'Lomé, Togo', items: cart.map(i => ({productId: i.id, quantity: i.quantity})), notes: 'Demande envoyée depuis le catalogue' }) }); if (response.ok) { setCart([]); setSent(true); } };
  return <><header><div className="brand">Togo<span>×</span>China</div><nav><a href="#catalogue">Catalogue</a><a href="#fonctionnement">Comment ça marche</a><button className="cart">Panier ({cart.length})</button></nav></header><main><section className="hero"><div><p className="eyebrow">IMPORTER PLUS SIMPLEMENT</p><h1>Vos fournisseurs chinois,<br/><em>à portée de main.</em></h1><p className="lead">Trouvez des produits compétitifs et faites-vous accompagner par nos agents jusqu'à Lomé.</p><a className="primary" href="#catalogue">Explorer le catalogue →</a></div><div className="hero-card"><div className="flag">🇹🇬</div><strong>Togo → Chine</strong><small>Un pont commercial fiable</small></div></section><section id="catalogue" className="catalogue"><div className="section-heading"><div><p className="eyebrow">CATALOGUE FOURNISSEURS</p><h2>Des produits pour développer votre commerce</h2></div><div className="filters"><input placeholder="Rechercher un produit" value={search} onChange={e => setSearch(e.target.value)}/><select value={category} onChange={e => setCategory(e.target.value)}><option>Toutes</option><option>Électronique</option><option>Maison</option><option>Mode</option></select></div></div><div className="grid">{products.map(p => <article className="product" key={p.id}><img src={p.imageUrl} alt={p.name}/><div className="product-body"><span>{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="product-footer"><strong>À partir de {p.unitPrice} $</strong><button onClick={() => add(p)}>Ajouter</button></div><small>Minimum : {p.minimumOrder} unités</small></div></article>)}</div></section><section id="fonctionnement" className="how"><p className="eyebrow">SIMPLE ET TRANSPARENT</p><h2>De la recherche à la livraison</h2><div className="steps"><div><b>01</b><h3>Trouvez</h3><p>Parcourez les produits sélectionnés pour les besoins du marché togolais.</p></div><div><b>02</b><h3>Demandez un devis</h3><p>Ajoutez vos produits et recevez une estimation personnalisée d'un agent.</p></div><div><b>03</b><h3>Recevez à Lomé</h3><p>Nous coordonnons l'achat et la logistique jusqu'à votre destination.</p></div></div></section></main>{cart.length > 0 && <aside><strong>{cart.length} produit(s) dans votre demande</strong><button className="primary" onClick={submit}>Demander un devis</button></aside>}{sent && <div className="toast">✓ Demande envoyée. Un agent vous contactera bientôt.</div>}<footer>Togo×China Marketplace · Votre partenaire d'importation</footer></>;
}
createRoot(document.getElementById('root')).render(<App />);
